services:
  api:
    container_name: nest-api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - ${NEST_API_PORT}:3000
    depends_on:
    - dev-db
    - test-db
    
  dev-db:
    container_name: dev-postgres-db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
    ports:
      - ${DEV_POSTGRES_PORT}:5432
    volumes:
      - ./docker-db-volumes/dev-db-volume:/var/lib/postgresql/data

  test-db:
    container_name: test-postgres-db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    ports:
      - ${TEST_POSTGRES_PORT}:5432