version: '3.8'

services:
  dev:
    container_name: fda-react-frontend
    image: fda-react-frontend:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
